dist: trusty
sudo: required

language: node_js
node_js:
  - "8"
  
branches:
  only:
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"


cache:
  directories:
     - ./node_modules
  yarn: true

install:
  - yarn install

script:
  - ng build --prod