dist: trusty
sudo: required

language: node_js
node_js:
  - "8"
  
branches:
  only:
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./node_modules
  npm: true

install:
  - npm install

script:
  - ng build --prod