language: node_js
sudo: true
dist: trusty

node_js:
   - “node”

branches:
   only:
      - master

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
      
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
   - npm install -g @angular/cli

script:
   - ng build --prod

after_success:
   - npm run deploy